name       : riscv-elf2hex
version    : 20.08.00.00
release    : 0
source     :
    - git|https://github.com/sifive/elf2hex.git : v20.08.00.00
license    : GPL-2.0-or-later
component  : system.devel
summary    : Converts ELF files to HEX files that are suitable for Verilog's readmemh
description: |
    Converts ELF files to HEX files that are suitable for Verilog's readmemh.
builddeps  :
    - riscv-gnu-toolchain
rundeps    :
    - riscv-gnu-toolchain
setup      : |
    %reconfigure --target=riscv64-unknown-elf
build      : |
    %make
install    : |
    %make_install
