name       : riscv-elf2hex
version    : 20.08.00.00
release    : 0
source     :
    - git|https://github.com/sifive/elf2hex.git : v20.08.00.00
license    :
    - GPL-2.0-or-later
component  : system.devel
summary    : GNU toolchain for RISC-V, including GCC
description: |
    GNU toolchain for RISC-V, including GCC
builddeps  :
    - riscv-gnu-toolchain
setup      : |
    autoreconf -i
    %configure --target=riscv64-unknown-elf
build      : |
    %make
install    : |
    %make_install